# Part 2

## Exercici 1

In [1]:
# importar llibreria pandas per poder llegir l'arxiu.

import pandas as pd

In [2]:
# carregar el dataset al notebook

df_delays = pd.read_csv(r'/home/marc/Documents/DelayedFlights.csv')

In [3]:
# Explorar el df. En primer lloc, busquem quines columnes cont√©

print(df_delays.columns.values)

['Unnamed: 0' 'Year' 'Month' 'DayofMonth' 'DayOfWeek' 'DepTime'
 'CRSDepTime' 'ArrTime' 'CRSArrTime' 'UniqueCarrier' 'FlightNum' 'TailNum'
 'ActualElapsedTime' 'CRSElapsedTime' 'AirTime' 'ArrDelay' 'DepDelay'
 'Origin' 'Dest' 'Distance' 'TaxiIn' 'TaxiOut' 'Cancelled'
 'CancellationCode' 'Diverted' 'CarrierDelay' 'WeatherDelay' 'NASDelay'
 'SecurityDelay' 'LateAircraftDelay']

In [4]:
# Seguim amb l'exploraci√≥ del df.

df_delays.describe()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1.936758e+06,1936758.0,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.929648e+06,1.936758e+06,1.936758e+06,...,1.936758e+06,1.929648e+06,1.936303e+06,1.936758e+06,1.936758e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06
mean,3.341651e+06,2008.0,6.111106e+00,1.575347e+01,3.984827e+00,1.518534e+03,1.467473e+03,1.610141e+03,1.634225e+03,2.184263e+03,...,7.656862e+02,6.812975e+00,1.823220e+01,3.268348e-04,4.003598e-03,1.917940e+01,3.703571e+00,1.502164e+01,9.013714e-02,2.529647e+01
std,2.066065e+06,0.0,3.482546e+00,8.776272e+00,1.995966e+00,4.504853e+02,4.247668e+02,5.481781e+02,4.646347e+02,1.944702e+03,...,5.744797e+02,5.273595e+00,1.433853e+01,1.807562e-02,6.314722e-02,4.354621e+01,2.149290e+01,3.383305e+01,2.022714e+00,4.205486e+01
min,0.000000e+00,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,...,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.517452e+06,2008.0,3.000000e+00,8.000000e+00,2.000000e+00,1.203000e+03,1.135000e+03,1.316000e+03,1.325000e+03,6.100000e+02,...,3.380000e+02,4.000000e+00,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,3.242558e+06,2008.0,6.000000e+00,1.600000e+01,4.000000e+00,1.545000e+03,1.510000e+03,1.715000e+03,1.705000e+03,1.543000e+03,...,6.060000e+02,6.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,8.000000e+00
75%,4.972467e+06,2008.0,9.000000e+00,2.300000e+01,6.000000e+00,1.900000e+03,1.815000e+03,2.030000e+03,2.014000e+03,3.422000e+03,...,9.980000e+02,8.000000e+00,2.100000e+01,0.000000e+00,0.000000e+00,2.100000e+01,0.000000e+00,1.500000e+01,0.000000e+00,3.300000e+01
max,7.009727e+06,2008.0,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.359000e+03,2.400000e+03,2.400000e+03,9.742000e+03,...,4.962000e+03,2.400000e+02,4.220000e+02,1.000000e+00,1.000000e+00,2.436000e+03,1.352000e+03,1.357000e+03,3.920000e+02,1.316000e+03

In [5]:
# Les columnes de retards contenen molts valors perduts (NaN). Suposarem que la falta de dades √©s perqu√® no es va 
# acumular un retard per aquell motiu. Per tant, substituirem els NaN per 0.

df_delays = df_delays.fillna(0)

In [6]:
# Reduir el dataset a 200.000 files (en t√© casi 2 milions). El nou df per treballar s'anomena df_vols. Es fa servir el m√®tode de pandas "sample".

df_vols = df_delays.sample(n=200000)

In [7]:
df_vols

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1009690,3388188,2008,6,24,2,2054.0,2045,2154.0,2140,MQ,...,3.0,19.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1711061,6360992,2008,11,28,5,1516.0,1500,1634.0,1625,AA,...,4.0,13.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1249618,4182637,2008,7,19,6,1251.0,1146,1532.0,1422,CO,...,5.0,26.0,0,N,0,0.0,0.0,70.0,0.0,0.0
1927411,6981211,2008,12,18,4,1247.0,1240,1717.0,1717,CO,...,9.0,20.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1080,1473,2008,1,3,4,2143.0,2045,2143.0,2050,WN,...,4.0,5.0,0,N,0,8.0,0.0,0.0,0.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1113406,3708254,2008,7,11,5,1112.0,1040,1433.0,1359,XE,...,12.0,15.0,0,N,0,0.0,0.0,14.0,0.0,20.0
648088,2082323,2008,4,1,2,921.0,900,1226.0,1220,WN,...,3.0,8.0,0,N,0,0.0,0.0,0.0,0.0,0.0
335166,1058394,2008,2,26,2,852.0,820,1004.0,925,AA,...,5.0,15.0,0,N,0,32.0,0.0,7.0,0.0,0.0
203633,654977,2008,2,18,1,1944.0,1935,2136.0,2150,WN,...,4.0,10.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1837919,6744566,2008,12,19,5,1502.0,1319,1606.0,1424,DL,...,12.0,8.0,0,N,0,102.0,0.0,0.0,0.0,0.0

## Exercici 2

In [8]:
# Analitzar estad√≠sticament el dataset. 

companyies = df_vols.UniqueCarrier.unique()

print(companyies)
print(len(companyies))

['MQ' 'AA' 'CO' 'WN' 'OH' '9E' 'DL' 'NW' 'F9' 'US' 'AS' 'FL' 'YV' 'OO'
 'XE' 'UA' 'B6' 'EV' 'HA' 'AQ']
20

In [9]:
print("El retard mitj√† de cada vol va ser de " + str(round(df_vols.ArrDelay.mean(), 2)) + " minuts.")

El retard mitj√† de cada vol va ser de 42.08 minuts.

In [10]:
print("La duraci√≥ mitjana de cada vol va ser de " + str(round(df_vols.AirTime.mean(), 2)) + " minuts.")
print("La desviaci√≥ mitjana de la duraci√≥ de vol va ser de  " + str(round(df_vols.AirTime.std(), 2)) + " minuts.")
print("Com que √©s un valor molt alt, pot ser interessant observar el valor de la mediana. La mediana de la duraci√≥ de vol va ser de " + str(round(df_vols.AirTime.median(), 2)) + " minuts.")

La duraci√≥ mitjana de cada vol va ser de 107.8 minuts.
La desviaci√≥ mitjana de la duraci√≥ de vol va ser de  68.96 minuts.
Com que √©s un valor molt alt, pot ser interessant observar el valor de la mediana. La mediana de la duraci√≥ de vol va ser de 90.0 minuts.

In [11]:
df_vols.describe()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,...,Distance,TaxiIn,TaxiOut,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,2.000000e+05,200000.0,200000.000000,200000.000000,200000.00000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,...,200000.000000,200000.000000,200000.000000,200000.00000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,3.341464e+06,2008.0,6.111155,15.794165,3.98343,1519.968720,1469.488855,1603.937440,1635.127285,2183.648710,...,765.367675,6.786125,18.242890,0.00036,0.003955,12.366540,2.371055,9.677855,0.053720,16.355830
std,2.062898e+06,0.0,3.476442,8.773776,1.99592,452.116972,425.575527,558.015114,465.845841,1944.414725,...,574.876481,5.316971,14.315575,0.01897,0.062764,35.581871,16.834071,28.072262,1.531952,35.990056
min,4.000000e+00,2008.0,1.000000,1.000000,1.00000,1.000000,0.000000,0.000000,0.000000,1.000000,...,31.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.524133e+06,2008.0,3.000000,8.000000,2.00000,1204.000000,1135.000000,1312.000000,1325.000000,612.000000,...,338.000000,4.000000,10.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.245097e+06,2008.0,6.000000,16.000000,4.00000,1547.000000,1510.000000,1714.000000,1708.000000,1543.000000,...,606.000000,5.000000,14.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,4.967715e+06,2008.0,9.000000,23.000000,6.00000,1902.000000,1820.000000,2031.000000,2015.000000,3421.000000,...,997.000000,8.000000,21.000000,0.00000,0.000000,10.000000,0.000000,6.000000,0.000000,18.000000
max,7.009655e+06,2008.0,12.000000,31.000000,7.00000,2400.000000,2359.000000,2400.000000,2400.000000,9742.000000,...,4962.000000,207.000000,422.000000,1.00000,1.000000,1369.000000,868.000000,890.000000,284.000000,805.000000

### Observem com els retards m√©s grans es donen per culpa de la companyia a√®ria i per l'arribada tardana de l'aparell. En ambd√≥s casos el responsable n'√©s l'operador.

In [12]:
# Busquem quina aerolinia va tenir m√©s retards de mitjana

retards_mitjans = df_vols.groupby("UniqueCarrier")["ArrDelay"].mean()

In [13]:
# Els ordenem per veure el superior. 

retards_mitjans.sort_values(ascending = False)

UniqueCarrier
YV    55.954344
B6    54.935278
XE    50.642030
OH    50.470632
UA    47.818855
EV    46.934749
9E    46.741032
AA    46.537887
OO    45.414348
MQ    44.494114
FL    44.450620
NW    43.615099
CO    40.080953
DL    39.125942
US    36.298123
AS    35.983923
HA    32.836627
WN    29.956814
F9    28.436867
AQ    15.539683
Name: ArrDelay, dtype: float64

In [14]:
# Hi ha molta difer√®ncia entre els retards de B6 i YV i els de F9 i AQ. Podria ser per la dist√†ncia dels seus vols. Comprove'm-ho.

distancies_mitjanes = df_vols.groupby("UniqueCarrier")["Distance"].mean()

distancies_mitjanes.sort_values(ascending = False)

UniqueCarrier
CO    1227.616210
B6    1111.462547
AA    1084.589284
UA    1083.242455
DL     974.921866
US     968.357553
AQ     954.285714
HA     949.287220
AS     944.853079
F9     896.116138
NW     829.678240
FL     726.185261
WN     646.864710
XE     601.283140
OH     512.250277
9E     464.346442
EV     463.031254
OO     438.975965
MQ     429.137802
YV     407.222556
Name: Distance, dtype: float64

### YV √©s la pitjor companyia a√®ria pel que fa als retards. Fa els vols de menor dist√†ncia i, tot i aix√≠, √©s la segona companyia que m√©s retards acumula. F9, a l'altre extrem, fa viatges entre mitjans i llargs i, en canvi, √©s la segona que menys retards acumula.

In [15]:
# Quins s√≥n els viatges m√©s llargs?

df_vols_llargs = df_vols.sort_values(by = ["Distance"], ascending = False)

df_vols_llargs.head(10)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
556357,1742522,2008,3,7,5,2258.0,2245,1409.0,1310,CO,...,15.0,15.0,0,N,0,13.0,0.0,46.0,0.0,0.0
362852,1140385,2008,2,20,3,1331.0,1320,1941.0,1920,CO,...,5.0,16.0,0,N,0,11.0,0.0,10.0,0.0,0.0
1921778,6971276,2008,12,31,3,1341.0,1335,1944.0,1935,CO,...,4.0,52.0,0,N,0,0.0,0.0,0.0,0.0,0.0
556375,1742561,2008,3,15,6,1340.0,1320,1806.0,1820,CO,...,5.0,17.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1520580,5364663,2008,9,10,3,1349.0,1335,1815.0,1810,CO,...,4.0,34.0,0,N,0,0.0,0.0,0.0,0.0,0.0
173822,566875,2008,1,11,5,1344.0,1320,1947.0,1920,CO,...,6.0,28.0,0,N,0,24.0,0.0,3.0,0.0,0.0
1727415,6438048,2008,11,14,5,1349.0,1335,1940.0,1935,CO,...,8.0,21.0,0,N,0,0.0,0.0,0.0,0.0,0.0
1619712,5906278,2008,10,24,5,2020.0,1955,1155.0,1130,CO,...,10.0,20.0,0,N,0,25.0,0.0,0.0,0.0,0.0
1518808,5355422,2008,9,2,2,1342.0,1335,1802.0,1810,CO,...,6.0,27.0,0,N,0,0.0,0.0,0.0,0.0,0.0
871328,2953089,2008,5,28,3,1530.0,1335,2028.0,1810,CO,...,8.0,40.0,0,N,0,6.0,0.0,23.0,0.0,109.0

In [19]:
df_vols_llargs[["Origin", "Dest", "Distance", "AirTime"]].head(10)

        Origin Dest  Distance  AirTime
556357     HNL  EWR      4962    581.0
362852     EWR  HNL      4962    649.0
1921778    EWR  HNL      4962    607.0
556375     EWR  HNL      4962    604.0
1520580    EWR  HNL      4962    588.0
173822     EWR  HNL      4962    629.0
1727415    EWR  HNL      4962    622.0
1619712    HNL  EWR      4962    545.0
1518808    EWR  HNL      4962    587.0
871328     EWR  HNL      4962    610.0

## Exercici 3

In [16]:
# Exportem el df_vols a Excel

df_vols.to_excel(r'/home/marc/Documents/mostra_vols.xlsx')